/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class Functions */

#ifndef _Included_Functions
#define _Included_Functions
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     Functions
 * Method:    sum
 * Signature: (II)I
 */
JNIEXPORT jint JNICALL Java_Functions_sum
  (JNIEnv *, jobject, jint, jint);

/*
 * Class:     Functions
 * Method:    subtraction
 * Signature: (II)I
 */
JNIEXPORT jint JNICALL Java_Functions_subtraction
  (JNIEnv *, jobject, jint, jint);

/*
 * Class:     Functions
 * Method:    division
 * Signature: (II)I
 */
JNIEXPORT jint JNICALL Java_Functions_division
  (JNIEnv *, jobject, jint, jint);

/*
 * Class:     Functions
 * Method:    multiplication
 * Signature: (II)I
 */
JNIEXPORT jint JNICALL Java_Functions_multiplication
  (JNIEnv *, jobject, jint, jint);

/*
 * Class:     Functions
 * Method:    pow
 * Signature: (II)I
 */
JNIEXPORT jint JNICALL Java_Functions_pow
  (JNIEnv *, jobject, jint, jint);

#ifdef __cplusplus
}
#endif
#endif
